version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/ActiveState/gometalinter-helper
    steps:
      - checkout
      - restore_cache:
          keys:
            - pkg
      - run:
          name: Install deps
          command: ./install-deps.sh
      - save_cache:
          paths:
            - /go/pkg
          key: pkg
      - run:
          name: Build
          command: go build ./cmd/gometalinter-helper
      - run:
          name: Self-check
          command: ./self-check.sh ./gometalinter-helper
